### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by zhovner** [raw-packet/raw-packet#50]
Current installation manual for macOS looks ugly. It can be much better with Homebrew tap.

How to setup homebrew tap:

1. Create additional repository on github with `homebrew` prefix in name.  
For example `homebrew-raw-packet`. 
Final path should look like this `github.com/raw-packet/homebrew-raw-packet`

2. Add homebrew formula file in this repository with name `raw-packet.rb`. All dependencies like wireshark can be added in this formula.

After all, installation manual should look like this:

```
brew tap raw-packet/raw-packet

brew install raw-packet
```

More beautiful.

**Comment by Vladimir-Ivanov-Git** [comment]
https://github.com/raw-packet/homebrew-raw-packet/blob/master/raw-packet.rb

**Comment by amanEdris** [comment]
brew install not working on catalina 10.15.6.  when running command it returns.

```
**(base) MacBook-Pro:~ dd$** apple_mitm --help
Traceback (most recent call last):
  File "/usr/local/Cellar/raw-packet/0.2.1/libexec/bin/apple_mitm", line 33, in <module>
    sys.exit(load_entry_point('raw-packet==0.2.1', 'console_scripts', 'apple_mitm')())
  File "/usr/local/Cellar/raw-packet/0.2.1/libexec/bin/apple_mitm", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: raw-packet
```
